# Generated by Django 2.2 on 2019-10-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlier_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('sensor', models.CharField(max_length=10)),
            ],
        ),
    ]
