# Generated by Django 2.2 on 2019-10-14 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plc', '0002_outlier_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outlier_data',
            old_name='humidity',
            new_name='value',
        ),
        migrations.RemoveField(
            model_name='outlier_data',
            name='temperature',
        ),
    ]
